Improve discovery flow
fixes #45

no longer fails if file is empty

diff --git a/scripts/discover/as-dns-resolution b/scripts/discover/as-dns-resolution
--- a/scripts/discover/as-dns-resolution
+++ b/scripts/discover/as-dns-resolution
@@ -23,20 +23,24 @@ if [ ! -z "$1" ]; then
 fi
 set -euo pipefail
 mkdir -p recon/domains
-
 find recon/domains/ -maxdepth 1 -type d  | tail -n +2 | while read domain_path; do
-  RECON_FILE="$domain_path/resolv-domains.txt"
-  if [[ ! -f "$RECON_FILE" ]] || [[ ! -s "$RECON_FILE" ]] ; then
-    mkdir -p "$(dirname $RECON_FILE)"
-    root_domain=$(basename "$domain_path")
-    _ 'Resoving domains for "'$root_domain'"'
-    fast-resolv -c $FR_THREADS -d "$domain_path/subdomains.txt" | tee "$RECON_FILE"
-    cat "$RECON_FILE" | sort > sorted
-    mv sorted "$RECON_FILE"
+  # make sure we have subdomains to process
+  if [ -s "$domain_path/subdomains.txt" ]; then
+    RECON_FILE="$domain_path/resolv-domains.txt"
+    if [[ ! -f "$RECON_FILE" ]] || [[ ! -s "$RECON_FILE" ]] ; then
+      mkdir -p "$(dirname $RECON_FILE)"
+      root_domain=$(basename "$domain_path")
+      _ 'Resoving domains for "'$root_domain'"'
+      fast-resolv -c $FR_THREADS -d "$domain_path/subdomains.txt" | tee "$RECON_FILE"
+      cat "$RECON_FILE" | sort > sorted
+      mv sorted "$RECON_FILE"
+    fi
   fi
 done
 
-if compgen -G "recon/domains/*/resolv-domains.txt" ; then
+# lets not fail if there are no valid resolutions
+set +o pipefail
+if compgen -G "recon/domains/*/resolv-domains.txt" > /dev/null; then
   cat recon/domains/*/resolv-domains.txt \
   | grep -P "has address|an alias" \
   | awk '{print $1}' \
