yolo
Lots of changes
but should mostly work

diff --git a/scripts/recon/40_content-discovery b/scripts/recon/40_content-discovery
--- a/scripts/recon/40_content-discovery
+++ b/scripts/recon/40_content-discovery
@@ -20,6 +20,11 @@ if [ -z "$CMD" ] ; then
   CMD="scan"
 fi
 
+GIT=1
+if [ ! -d .git ]; then
+  GIT=0
+fi
+
 
 #set -euo pipefail
 set -eu
@@ -28,10 +33,36 @@ WEB_PORTS="(80|443|3000|8000|8001|8080|8443)"
 WEB_PORT_REGEX="portid=\"$WEB_PORTS\"|tcp/$WEB_PORTS"
 
 
+function gitPull {
+  if [ $GIT -eq 1 ]; then
+    if ! git pull > /dev/null 2>&1 ; then
+      echo "[!] pull failed" >&2
+    fi
+  fi
+}
+
+function gitCommit {
+  if [ $GIT -eq 1 ]; then
+    path="$1"
+    msg="$2"
+    git add "$path"
+
+    if git commit -m "$msg" ; then
+      if ! git pull --rebase ; then
+        git commit -am "wtf is this..."
+        git pull --rebase
+      fi
+      git push
+    else
+      echo "nothing happened"
+    fi
+  fi
+}
+
 function newGetHostUrls {
   cat hosts/*/recon/*hostnames.txt \
   | sort -u \
-  | ar-prune-blacklisted-domains \
+  | as-prune-blacklisted-domains \
   | grep -vP "(//((sso\.|scm\.)?azurewebsites\.net|(sso\.|scm\.)?azure\-mobile\.net|s3\.amazonaws\.com)$)|((\.secureserver\.net|\.microsoftonline\.com|windows\.net|amazonaws\.com|hscoscdn)$)"  \
   | while read hostname; do
 
@@ -41,8 +72,10 @@ function newGetHostUrls {
       echo "no host found for hostname: $hostname"
     fi
 
-
-    draft=$(grep draft "hosts/$host/README.md" || echo "nope")
+    draft="nope"
+    if [ -f "hosts/$host/00_metadata.md" ] ; then
+      draft=$(grep draft "hosts/$host/00_metadata.md" || echo "nope")
+    fi
     if [ "$draft" == "nope" ]; then
 
       if grep -P "$WEB_PORT_REGEX" hosts/$host/recon/nmap-* > /dev/null 2>&1; then
@@ -76,7 +109,6 @@ function newGetHostUrls {
   done | sort -h | uniq
 }
 
-
 function getHostnames {
   SKIP_IP=0
   if ! grep -rP "\.amazonaws\.com|\.windows\.net" . > /dev/null 2>&1 ; then
@@ -99,17 +131,22 @@ function getHostnames {
 }
 
 function scanHost {
+  set +u
   host="$1"
   url="$2"
+  set -u
+
   echo "[+] Checking $host $url"
 
-
-  draft=$(grep draft "hosts/$host/README.md" || echo "nope")
+  draft="nope"
+  if [ -f "hosts/$host/00_metadata.md" ] ; then
+    draft=$(grep draft "hosts/$host/00_metadata.md" || echo "nope")
+  fi
   if [ "$draft" == "nope" ]; then
     cd "hosts/$host"
     output_file="gobuster.$(echo "$url" | sed "s/:\/\//./" | sed 's/\//\./g').$wordlist_name.txt"
 
-    # git pull
+    gitPull
     if [ ! -f "recon/$output_file" ] ; then
       echo "[+] Scanning $host $url"
       if [ ! -z $CHECK_ONLY ]; then
@@ -122,37 +159,21 @@ function scanHost {
           echo "s3" > $output_file
         else
           echo lock > "recon/$output_file"
-          ar-update-flags.sh git
-          git add .
-          git commit -m "start gobuster $url"
-
-          if ! git pull --rebase ; then
-            echo not sure what happened... help
-            exit
-          fi
-          git push
+          gitCommit "." "start gobuster $url"
 
           set +o pipefail
           set +e
 
-          arbuster -k -e -a Firefox -u $url -w $wordlist_file
+          as-buster -k -e -a Firefox -u $url -w $wordlist_file
         fi
 
-        git add .
-        git commit -m "gobuster end $url"
-
-        if ! git pull --rebase ; then
-          echo not sure what happened... help
-          exit
-        fi
-        git push
+        gitCommit "." "end gobuster $url"
         set -e
         set -o pipefail
       fi
     fi
     cd - > /dev/null
   fi
-
 
   if [ $MANUAL -eq 0 ]; then
     ARGS=$(head -n1 <<<$($ME list | grep -v "no host found"))
@@ -161,10 +182,17 @@ function scanHost {
       ARG_URL=$(echo "$ARGS" | awk '{print $2}')
       exec $ME scan
     fi
+    if grep lock hosts/*/recon/gobuster.* > /dev/null; then
+      exit 1
+    fi
   fi
 }
 
-wordlist_file=$(realpath "recon/gobuster-initial.txt")
+if [ ! -f "recon/wordlist-content-discovery.txt" ]; then
+  as-wordlist content-discovery > "recon/wordlist-content-discovery.txt"
+fi
+
+wordlist_file=$(realpath "recon/wordlist-content-discovery.txt")
 wordlist_name=`basename $wordlist_file`
 wordlist_name="${wordlist_name%.*}"
 
@@ -186,6 +214,12 @@ if [ "$CMD" == "scan" ] ; then
     ARGS=$(head -n1 <<<$($ME list | grep -v "no host found" | sort -R))
     ARG_HOST=$(echo "$ARGS" | awk '{print $1}')
     ARG_URL=$(echo "$ARGS" | awk '{print $2}')
+    if [ "$ARG_HOST" == "" ]; then
+      if grep lock hosts/*/recon/gobuster.* > /dev/null; then
+        exit 1
+      fi
+      exit
+    fi
     echo "[!] Auto selected $ARG_HOST $ARG_URL"
   fi
   scanHost $ARG_HOST $ARG_URL
diff --git a/scripts/recon/80_http-screenshot b/scripts/recon/80_http-screenshot
--- a/scripts/recon/80_http-screenshot
+++ b/scripts/recon/80_http-screenshot
@@ -14,14 +14,45 @@ if [ -z "$CMD" ] ; then
   CMD="scan"
 fi
 
+GIT=1
+if [ ! -d .git ]; then
+  GIT=0
+fi
+
 set -euo pipefail
 
 WEB_PORTS="80,443,3000,8000,8001,8080,8443"
 
+function gitPull {
+  if [ $GIT -eq 1 ]; then
+    if ! git pull > /dev/null 2>&1 ; then
+      echo "[!] pull failed" >&2
+    fi
+  fi
+}
+
+function gitCommit {
+  if [ $GIT -eq 1 ]; then
+    path="$1"
+    msg="$2"
+    git add "$path"
+
+    if git commit -m "$msg" ; then
+      if ! git pull --rebase ; then
+        git commit -am "wtf is this..."
+        git pull --rebase
+      fi
+      git push
+    else
+      echo "nothing happened"
+    fi
+  fi
+}
+
 function getURLs {
   {
     set +o pipefail
-    cat recon/*.gobuster-initial.txt \
+    cat recon/*.wordlist-content-discovery.txt \
     | grep -P "Status: 2"  \
     | grep -viP "\.(png|jpe?g|ico|css|gif|js)$"
     set -o pipefail
@@ -31,13 +62,11 @@ function getURLs {
 }
 
 function getHosts {
-  if ! git pull > /dev/null 2>&1 ; then
-    echo "[!] pull failed" >&2
-  fi
+  gitPull
 
    {
-     find hosts -name 'gobuster.*.gobuster-initial.txt' -size +0 | cut -d/ -f2 | sort -h | uniq
-     find hosts -name 'aquatone-gobuster-initial.txt' | cut -d/ -f2 | sort -h | uniq
+     find hosts -name 'gobuster.*.wordlist-content-discovery.txt' -size +0 | cut -d/ -f2 | sort -h | uniq
+     find hosts -name 'wordlist-content-discovery.txt' | cut -d/ -f2 | sort -h | uniq
    } | sort | uniq -c | grep "1 " | awk '{print $2}' | while read host; do
    cd hosts/$host
     urls=$(getURLs | wc -l)
@@ -52,54 +81,22 @@ function scanHost {
   host="$1"
   echo checking $host
 
-  if [ ! -f "hosts/$host/recon/aquatone-gobuster-initial.txt" ] ; then
+  if [ ! -f "hosts/$host/recon/wordlist-content-discovery.txt" ] ; then
     echo preparing to aquatone $host
 
     cd "hosts/$host"
     getURLs \
-    | tee "recon/aquatone-gobuster-initial.txt"
+    | tee "recon/wordlist-content-discovery.txt"
 
-    git add .
-    git commit -m "aquatone start $host"
-    if ! git pull --rebase ; then
-      echo something went wrong help
-      exit
-    fi
-    if ! git push ; then
-      git pull --rebase
+    gitCommit "." "aquatone start $host"
 
-      if ! git push ; then
-        echo something went wrong help
-        exit
-      fi
-
-    fi
-
-    cat "recon/aquatone-gobuster-initial.txt" | aquatone -ports $WEB_PORTS -out recon/aquatone-gobuster-initial
-    ar-update-flags.sh git
+    cat "recon/wordlist-content-discovery.txt" | aquatone -ports $WEB_PORTS -out recon/aquatone-wordlist-content-discovery
     # remove UTF BOM, this fixes aquatone being rendered in hugo
     find . -name '*.html' -exec sed -i '1s/^\xEF\xBB\xBF//' {} \;
 
-    git add .
+    gitCommit "." "aquatone end $host"
+
     cd - > /dev/null
-
-    if git commit -m "aquatone end $host" ; then
-      if ! git pull --rebase ; then
-        echo something went wrong help
-        echo I was trying to pull before pushing up the aaquatone results
-        exit
-      fi
-      if ! git push ; then
-        git pull --rebase
-
-        if ! git push ; then
-          echo something went wrong help
-          exit
-        fi
-      fi
-    else
-      echo not sure what happened. but i couldnt commit
-    fi
   fi
 
   echo host check complete
@@ -124,6 +121,9 @@ fi
 if [ "$CMD" == "scan" ] ; then
   if [ -z "$ARG" ] ; then
     ARG=$(head -n1 <<<$(getHosts | sort -R))
+    if [ "$ARG" == "" ]; then
+      exit
+    fi
     echo "[!] Auto selected $ARG"
   fi
   scanHost "$ARG"
