better locks

diff --git a/scripts/recon/as-content-discovery b/scripts/recon/as-content-discovery
--- a/scripts/recon/as-content-discovery
+++ b/scripts/recon/as-content-discovery
@@ -45,11 +45,19 @@ function gitCommit {
   if [ $GIT -eq 1 ]; then
     path="$1"
     msg="$2"
+    mode="$3"
     git add "$path"
 
     if git commit -m "$msg" ; then
       if ! git pull --rebase ; then
-        git commit -am "wtf is this..."
+        echo '[!] pull rebase failed'
+        if [ "$mode" == "reset" ] ; then
+          echo '[!] reset to origin'
+          git reset --hard origin/master
+          exit 2
+        fi
+        echo '[!] not sure what to do. i guess i will git add and hope it works'
+        git commit -am "not sure what this is"
         git pull --rebase
       fi
       git push
@@ -157,9 +165,10 @@ function scanHost {
         # If the host points to an S3 bucket, we don't want to gobuster it
         if curl -sIL $host | grep -q "https://aws.amazon.com/s3/"; then
           echo "s3" > $output_file
+          gitCommit "recon/$output_file" "skip gobuster $url" reset
         else
           echo lock > "recon/$output_file"
-          gitCommit "." "start gobuster $url"
+          gitCommit "recon/$output_file" "start gobuster $url" reset
 
           set +o pipefail
           set +e
diff --git a/scripts/recon/as-http-screenshot-hosts b/scripts/recon/as-http-screenshot-hosts
--- a/scripts/recon/as-http-screenshot-hosts
+++ b/scripts/recon/as-http-screenshot-hosts
@@ -35,11 +35,19 @@ function gitCommit {
   if [ $GIT -eq 1 ]; then
     path="$1"
     msg="$2"
+    mode="$3"
     git add "$path"
 
     if git commit -m "$msg" ; then
       if ! git pull --rebase ; then
-        git commit -am "wtf is this..."
+        echo '[!] pull rebase failed'
+        if [ "$mode" == "reset" ] ; then
+          echo '[!] reset to origin'
+          git reset --hard origin/master
+          exit 2
+        fi
+        echo '[!] not sure what to do. i guess i will git add and hope it works'
+        git commit -am "not sure what this is"
         git pull --rebase
       fi
       git push
@@ -85,10 +93,12 @@ function scanHost {
     echo preparing to aquatone $host
 
     cd "hosts/$host"
+
+    echo lock > "recon/wordlist-content-discover.txt"
+    gitCommit "recon/wordlist-content-discover.txt" "aquatone start $host" reset
+
     getURLs \
     | tee "recon/wordlist-content-discover.txt"
-
-    gitCommit "." "aquatone start $host"
 
     cat "recon/wordlist-content-discover.txt" | aquatone -ports $WEB_PORTS -out recon/aquatone-wordlist-content-discover
     # remove UTF BOM, this fixes aquatone being rendered in hugo
diff --git a/scripts/recon/as-port-scan-tcp b/scripts/recon/as-port-scan-tcp
--- a/scripts/recon/as-port-scan-tcp
+++ b/scripts/recon/as-port-scan-tcp
@@ -35,11 +35,19 @@ function gitCommit {
   if [ $GIT -eq 1 ]; then
     path="$1"
     msg="$2"
+    mode="$3"
     git add "$path"
 
     if git commit -m "$msg" ; then
       if ! git pull --rebase ; then
-        git commit -am "wtf is this..."
+        echo '[!] pull rebase failed'
+        if [ "$mode" == "reset" ] ; then
+          echo '[!] reset to origin'
+          git reset --hard origin/master
+          exit 2
+        fi
+        echo '[!] not sure what to do. i guess i will git add and hope it works'
+        git commit -am "not sure what this is"
         git pull --rebase
       fi
       git push
@@ -67,8 +75,8 @@ function scanHost {
   if ! compgen -G "hosts/$host/recon/nmap-punched*tcp*" > /dev/null 2>&1; then
     mkdir -p "hosts/$host/recon"
     if [ ! -f "hosts/$host/recon/nmap-punched-quick-tcp.xml" ]; then
-      touch "hosts/$host/recon/nmap-punched-quick-tcp.xml"
-      gitCommit "hosts/$host/recon/" "new host: $host"
+      echo lock > "hosts/$host/recon/nmap-punched-quick-tcp.xml"
+      gitCommit "hosts/$host/recon/nmap-punched-quick-tcp.xml" "new host: $host" "reset"
     fi
 
     cd "hosts/$host"
